[project]
name = "aura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "environs>=11.2.1",
    "plotly>=5.24.1",
    "polars>=1.12.0",
    "selenium>=4.26.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.2",
]
